name: network_connectivity_checker
description: A sample command-line application.
version: 1.0.0
publish_to: none

environment:
  sdk: ^3.4.3

# Add regular dependencies here.
dependencies:
  # path: ^1.8.0
  scotch_dev_error:
    git:
      url: https://github.com/Flutter-Apps-pty/scotch_dev_error.git
      ref: feat/pepkor_mvp_codes

dev_dependencies:
  lints: ^3.0.0
  test: ^1.24.0
